### ISSUE TITLE
Just Citing/Acknowledging Your Work

### ISSUE THREAD

**Issue by anonhostpi** [0xC0000054/DBPFSharp#1]
*Gonna open then immediately close this issue.* Just reaching out to let you know that **my DBPF wiki cites this repository.**
- wiki: https://anonhostpi.github.io/DBPF.js/docs/other/spec/

I'm avidly working on my own DBPF reader. If you see anything missing from my wiki (...or my lib), feel free let me know! I'm avidly working on them every day

I just wanted to be sure you knew I was citing your work! Very interesting library. Nice to see a DBPF reader catered to SimCity. I feel like those games are often forgotten!

**Comment by 0xC0000054** [comment]
Thanks. 

Historically DBPF support is probably one of those things that many modders would write their own version of. You may have already seen [this](https://community.simtropolis.com/forums/topic/762189-simcity-4-open-access-repository-of-modding-tools/?tab=comments#comment-1777731) Simtropolis post with a list of other open-source DBPF code.
This library is split off from the DBPF library that I wrote years ago for my SC4 texture modding tools: https://github.com/0xC0000054/FshDatIO
Ilive's Reader is another implementation written in C++, https://sourceforge.net/p/ilive-reader/code/HEAD/tree/trunk/or_dat/sim015.cpp

I am surprised at how long EA/Maxis have continued to use the DBPF format.

There is a [post](https://community.simtropolis.com/forums/topic/25824-legal-status-of-sim-city-4-mods/?do=findComment&comment=695104) by one of the early SC4 modders regarding the efforts EA/Maxis went to to support them.
EA paid to bring a number of the early SC4 modders out to San Francisco to discuss that topic, and several modders had entered Non disclosure agreements with EA/Maxis to further file modifications.

**Comment by anonhostpi** [comment]
I was hoping to centralize it a bit by offering an updated and more centralized wiki tailored to TS4.

I'm also working on some tooling for generating JSON Metadata files for DBPF entry types that pulls from the wiki. The idea is to make it easier for other devs to write their own readers in whatever languages they want.

**Comment by anonhostpi** [comment]
I'm also now working on [Kaitai](https://doc.kaitai.io/) tooling as well for entries:
- see: https://github.com/anonhostpi/DBPF.js/blob/main/docs/spec/sections/ResourceTypes.md#structure
  - which generates: https://github.com/anonhostpi/DBPF.js/blob/main/src/Plugins/ResourceTypes/GEOM/geom.ksy
    - using `node scripts/resources.js`
